# Generated by Django 4.1.3 on 2022-12-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Todo',
        ),
    ]
